sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

cache:
  pip: true
  apt: true

env:
  global:
    - TEST_DB_SERVICE=1 TEST_WITH_EXTENSIONS=1
  matrix:
 
    - ODOO_VERSION="10.0"
      ODOO_RELEASE="10.0"
      ODOO_PACKAGE="odoo"
      ODOO_TEST_PROTOCOL='xml-rpc'
      TEST_SKIP_WORKFLOW=1

    - ODOO_VERSION="10.0"
      ODOO_RELEASE="10.0"
      ODOO_PACKAGE="odoo"
      ODOO_TEST_PROTOCOL='json-rpc'
      TEST_SKIP_WORKFLOW=1

    - ODOO_VERSION="11.0"
      ODOO_RELEASE="11.0"
      ODOO_PACKAGE="odoo"
      ODOO_TEST_PROTOCOL='xml-rpc'
      TEST_SKIP_WORKFLOW=1

    - ODOO_VERSION="11.0"
      ODOO_RELEASE="11.0"
      ODOO_PACKAGE="odoo"
      ODOO_TEST_PROTOCOL='json-rpc'
      TEST_SKIP_WORKFLOW=1

install:
  - "wget http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/${ODOO_PACKAGE}_${ODOO_RELEASE}.latest_all.deb -O odoo.deb"
  - "! command -v wkhtmltopdf >/dev/null 2>&1 && wget ${WKHTMLTOPDF_URL} -O wkhtmltox.deb"
  - "! command -v wkhtmltopdf >/dev/null 2>&1 && sudo dpkg --force-depends -i wkhtmltox.deb"
  - "sudo apt-get update && sudo apt-get install -f -y"
  - "sudo apt-get install -y $(dpkg -I odoo.deb | grep -o -P 'Depends: \\K(.*)' | tr ',' ' ') || true"
  - "sudo dpkg --force-depends -i odoo.deb || true"
  - "pip install --upgrade 'coveralls>=1.1' 'ipython[notebook]>=4' 'setuptools>=18' pip pbr 'anyfield>=0.1.2' 'flake8>=3'"
  - "python setup.py develop"

before_script:
  - "sudo invoke-rc.d ${ODOO_PACKAGE} restart"
  - "sleep 3"

script:
  - "flake8 openerp_proxy --count --statistics;"  # test code style
  - "openerp_proxy <<< 'print(42);exit';"  # Test that it runs via 'openerp_proxy' command
  - "coverage run -p setup.py test"
  - "coverage combine"

after_success:
  - coveralls
